const treeData = [
  {
    id: "0",
    label: "全部分类",
    data: [
      {
        label: "个人敏感信息",
        field: "",
        value: "1",
        id: "group_1",
        total: 16,
        isLeaf: false,
        description: "个人敏感信息",
        data: [
          {
            label: "车辆识别代码",
            field: "",
            value: "11",
            id: "dict_11",
            total: 1,
            isLeaf: true,
            selected: true,
            level: 2,
            description: "车辆识别代码",
            data: null,
          },
          {
            label: "车牌号（中国内地）",
            field: "",
            value: "12",
            id: "dict_12",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "车牌号（中国内地）",
            data: null,
          },
          {
            label: "储蓄卡(银行卡)",
            field: "",
            value: "13",
            id: "dict_13",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "储蓄卡(银行卡)",
            data: null,
          },
          {
            label: "宗教信仰",
            field: "",
            value: "14",
            id: "dict_14",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "宗教信仰",
            data: null,
          },
          {
            label: "军官证",
            field: "",
            value: "15",
            id: "dict_15",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "军官证",
            data: null,
          },
          {
            label: "护照号（中国内地）",
            field: "",
            value: "16",
            id: "dict_16",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "护照号（中国内地）",
            data: null,
          },
          {
            label: "民族",
            field: "",
            value: "17",
            id: "dict_17",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "民族",
            data: null,
          },
          {
            label: "邮箱",
            field: "",
            value: "18",
            id: "dict_18",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "邮箱",
            data: null,
          },
          {
            label: "SSN",
            field: "",
            value: "19",
            id: "dict_19",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "SSN",
            data: null,
          },
          {
            label: "性别",
            field: "",
            value: "20",
            id: "dict_20",
            total: 1,
            isLeaf: true,
            level: 1,
            description: "性别",
            data: null,
          },
          {
            label: "港澳通行证",
            field: "",
            value: "21",
            id: "dict_21",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "港澳通行证",
            data: null,
          },
          {
            label: "身份证（中国香港）",
            field: "",
            value: "22",
            id: "dict_22",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "身份证（中国香港）",
            data: null,
          },
          {
            label: "电话号码（中国内地）",
            field: "",
            value: "23",
            id: "dict_23",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "电话号码（中国内地）",
            data: null,
          },
          {
            label: "身份证（中国内地）",
            field: "",
            value: "24",
            id: "dict_24",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "身份证（中国内地）",
            data: null,
          },
          {
            label: "手机号（中国内地）",
            field: "",
            value: "25",
            id: "dict_25",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "手机号（中国内地）",
            data: null,
          },
          {
            label: "信用卡",
            field: "",
            value: "26",
            id: "dict_26",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "信用卡",
            data: null,
          },
        ],
      },
      {
        label: "位置敏感信息",
        field: "",
        value: "2",
        id: "group_2",
        total: 2,
        isLeaf: false,
        description: "位置敏感信息",
        data: [
          {
            label: "省份（中国内地）",
            field: "",
            value: "27",
            id: "dict_27",
            total: 1,
            isLeaf: true,
            level: 1,
            description: "省份（中国内地）",
            data: null,
          },
          {
            label: "GPS位置",
            field: "",
            value: "28",
            id: "dict_28",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "GPS位置",
            data: null,
          },
        ],
      },
      {
        label: "设备敏感信息",
        field: "",
        value: "3",
        id: "group_3",
        total: 7,
        isLeaf: false,
        description: "设备敏感信息",
        data: [
          {
            label: "JDBC连接串",
            field: "",
            value: "4",
            id: "dict_4",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "JDBC连接串",
            data: null,
          },
          {
            label: "IPv6地址",
            field: "",
            value: "5",
            id: "dict_5",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "IPv6地址",
            data: null,
          },
          {
            label: "IMEI",
            field: "",
            value: "6",
            id: "dict_6",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "IMEI",
            data: null,
          },
          {
            label: "IPv4地址",
            field: "",
            value: "7",
            id: "dict_7",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "IPv4地址",
            data: null,
          },
          {
            label: "MAC地址",
            field: "",
            value: "8",
            id: "dict_8",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "MAC地址",
            data: null,
          },
          {
            label: "MEID",
            field: "",
            value: "9",
            id: "dict_9",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "MEID",
            data: null,
          },
          {
            label: "URL链接",
            field: "",
            value: "10",
            id: "dict_10",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "URL链接",
            data: null,
          },
        ],
      },
      {
        label: "企业敏感信息",
        field: "",
        value: "4",
        id: "group_4",
        total: 2,
        isLeaf: false,
        description: "企业敏感信息",
        data: [
          {
            label: "统一社会信用代码",
            field: "",
            value: "2",
            id: "dict_2",
            total: 1,
            isLeaf: true,
            level: 1,
            description: "统一社会信用代码",
            data: null,
          },
          {
            label: "税务登记证号码",
            field: "",
            value: "3",
            id: "dict_3",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "税务登记证号码",
            data: null,
          },
        ],
      },
      {
        label: "通用敏感数据",
        field: "",
        value: "5",
        id: "group_5",
        total: 1,
        isLeaf: false,
        description: "通用敏感数据",
        data: [
          {
            label: "日期",
            field: "",
            value: "1",
            id: "dict_1",
            total: 1,
            isLeaf: true,
            level: 1,
            description: "日期",
            data: null,
          },
        ],
      },
      {
        label: "密钥敏感信息",
        field: "",
        value: "6",
        id: "group_6",
        total: 7,
        isLeaf: false,
        description: "密钥敏感信息",
        data: [
          {
            label: "PEM证书",
            field: "",
            value: "29",
            id: "dict_29",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "PEM证书",
            data: null,
          },
          {
            label: "KEY私钥",
            field: "",
            value: "30",
            id: "dict_30",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "KEY私钥",
            data: null,
          },
          {
            label: "哈希密码",
            field: "",
            value: "31",
            id: "dict_31",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "哈希密码",
            data: null,
          },
          {
            label: "OpenAI APIkey",
            field: "",
            value: "32",
            id: "dict_32",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "OpenAI APIkey",
            data: null,
          },
          {
            label: "GitHub 个人访问令牌",
            field: "",
            value: "33",
            id: "dict_33",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "GitHub 个人访问令牌",
            data: null,
          },
          {
            label: "Bearer Token",
            field: "",
            value: "34",
            id: "dict_34",
            total: 1,
            isLeaf: true,
            level: 3,
            description: "Bearer Token",
            data: null,
          },
          {
            label: "AccessKeyId",
            field: "",
            value: "35",
            id: "dict_35",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "AccessKeyId",
            data: null,
          },
        ],
      },
      {
        label: "报错敏感信息",
        field: "",
        value: "7",
        id: "group_7",
        total: 7,
        isLeaf: false,
        description: "报错敏感信息",
        data: [
          {
            label: "Mysql报错信息",
            field: "",
            value: "36",
            id: "dict_36",
            total: 1,
            isLeaf: true,
            level: 2,
            description:
              "MySQL 报错信息可能包含关于数据库结构、数据甚至敏感信息的线索，导致敏感信息泄露。",
            data: null,
          },
          {
            label: "Oracle报错信息",
            field: "",
            value: "37",
            id: "dict_37",
            total: 1,
            isLeaf: true,
            level: 2,
            description:
              "Oracle 报错信息可能包含关于数据库结构、数据和敏感信息的线索，导致敏感信息泄露。",
            data: null,
          },
          {
            label: "SQL Server报错信息",
            field: "",
            value: "38",
            id: "dict_38",
            total: 1,
            isLeaf: true,
            level: 2,
            description:
              "SQL Server 报错信息可能导致敏感信息泄露，攻击者可以利用这些信息来了解数据库的结构和敏感数据。",
            data: null,
          },
          {
            label: "PHP报错信息",
            field: "",
            value: "39",
            id: "dict_39",
            total: 1,
            isLeaf: true,
            level: 2,
            description:
              "PHP报错信息可能会包含敏感信息，例如服务器路径、用户名、密码或数据库信息等，这些信息可以被黑客用于攻击并入侵网站或服务器。",
            data: null,
          },
          {
            label: "Fastjson报错信息",
            field: "",
            value: "40",
            id: "dict_40",
            total: 1,
            isLeaf: true,
            level: 2,
            description:
              "Fastjson报错信息中可能包含敏感信息，例如变量名、类名和堆栈信息等。攻击者可以针对性地利用这些信息来发起攻击，例如反序列化和SQL注入等。",
            data: null,
          },
          {
            label: "Nginx报错信息",
            field: "",
            value: "41",
            id: "dict_41",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "Nginx版本号泄露",
            data: null,
          },
          {
            label: "Apache报错信息",
            field: "",
            value: "42",
            id: "dict_42",
            total: 1,
            isLeaf: true,
            level: 2,
            description: "Apache指纹信息泄露",
            data: null,
          },
        ],
      },
    ],
  },
];

function disabledTree(arr) {
  arr.forEach((el) => {
    el.selected = el.selected ? el.selected : false;
    disabledTree(el.data || []);
  });
}

disabledTree(treeData);
console.log("result: ", treeData);
export default treeData;
